version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: nmv
      POSTGRES_PASSWORD: coderhouse
      POSTGRES_DB: coderhouse_db
    ports:
      - "5432:5432"
    volumes:
      - ./csv:/opt/csv
      - ./initdb_postgres:/docker-entrypoint-initdb.d
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@coderhouse.com
      PGADMIN_DEFAULT_PASSWORD: coderhouse
    ports:
      - "5050:80"